# -*- coding: utf-8 -*-
"""linebot2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zJMDa0YJ5rHJ-tcR_7bzNg_H1YAv3kXx
"""

from google.colab import drive 
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/'My Drive'/'linebot'

!pip install pya3rt
!pip install line-bot-sdk
!pip install flask-ngrok

!curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

!heroku login

from flask import Flask, request, abort
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import MessageEvent, TextMessage, TextSendMessage
import pya3rt
from flask_ngrok import run_with_ngrok

app = Flask(__name__)
run_with_ngrok(app)
line_bot_api = LineBotApi('j/gSSSBiDuJ27Kv0pmKqp/a2p4VInR33bUxv/AvoDSfinpdx7RZZSaEJrGdNjDk8iRZBMsIUzoqDsuDxosaSQh5P7AUjaT7srGAkDa5L883FELLCXzJDccpKeQq50VVe/CLwQNDKwzIMhqe3XwrHPAdB04t89/1O/w1cDnyilFU=')
handler = WebhookHandler('d8a4317b795e4e51949bf9a79ad9823e')

@app.route("/callback", methods=['POST'])
def callback():
  signature = request.headers["X-Line-Signature"]
  body = request.get_data(as_text=True)

  try:
    handler.handle(body, signature)
  except InvalidSignatureError:
    abort(400)

  return 'OK'
  
@handler.add(MessageEvent, message=TextMessage)
def handle_messge(event):
  ai_message = talk_ai(event.message.text)
  line_bot_api.reply_message(event.reply_token, TextSendMessage(text=ai_message))

def talk_ai(word):
  apikey = "DZZdrAPYiGtmbAQoBqCVmDmhRb6XjaHv"
  client = pya3rt.TalkClient(apikey)
  reply_message = client.talk(word)
  return reply_message['results'][0]['reply']

if __name__ == '__main__':
  app.run()

